// <auto-generated />
using System;
using DataAccess.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(BuildHomeDBContext))]
    [Migration("20181128005407_inventory_tables")]
    partial class inventory_tables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAccess.Models.Customer", b =>
                {
                    b.Property<int>("CustID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("CustID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DataAccess.Models.CustReceiptDetail", b =>
                {
                    b.Property<int>("CustReceiptDetailID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("CustReceiptDetailID");

                    b.ToTable("CustReceiptDetails");
                });

            modelBuilder.Entity("DataAccess.Models.CustReceiptHead", b =>
                {
                    b.Property<int>("CustReceiptHeadID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustID");

                    b.HasKey("CustReceiptHeadID");

                    b.HasIndex("CustID");

                    b.ToTable("CustReceiptHeads");
                });

            modelBuilder.Entity("DataAccess.Models.GrnDetail", b =>
                {
                    b.Property<int>("GRNDetailID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GrnHeadID");

                    b.HasKey("GRNDetailID");

                    b.HasIndex("GrnHeadID");

                    b.ToTable("GrnDetails");
                });

            modelBuilder.Entity("DataAccess.Models.GrnHead", b =>
                {
                    b.Property<int>("GrnHeadID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("GrnHeadID");

                    b.ToTable("GrnHeads");
                });

            modelBuilder.Entity("DataAccess.Models.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsSerialized");

                    b.Property<int?>("ItemCategoryCatCode");

                    b.Property<string>("ItemName");

                    b.Property<double>("UnitPrice");

                    b.HasKey("ItemID");

                    b.HasIndex("ItemCategoryCatCode");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("DataAccess.Models.ItemCategory", b =>
                {
                    b.Property<int>("CatCode")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CatName");

                    b.HasKey("CatCode");

                    b.ToTable("ItemCategories");
                });

            modelBuilder.Entity("DataAccess.Models.ItemFac", b =>
                {
                    b.Property<int>("ItemFacID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ItemID");

                    b.Property<double>("Qty");

                    b.HasKey("ItemFacID");

                    b.ToTable("ItemFacs");
                });

            modelBuilder.Entity("DataAccess.Models.ItemFacInv", b =>
                {
                    b.Property<int>("ItemFacInvID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ItemFacID");

                    b.HasKey("ItemFacInvID");

                    b.ToTable("ItemFacInvs");
                });

            modelBuilder.Entity("DataAccess.Models.MiscExpencesDetail", b =>
                {
                    b.Property<int>("MiscExpencesDetailID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("MiscExpencesDetailID");

                    b.ToTable("MiscExpencesDetails");
                });

            modelBuilder.Entity("DataAccess.Models.MiscExpencesHead", b =>
                {
                    b.Property<int>("MiscExpencesHeadID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("MiscExpencesHeadID");

                    b.ToTable("MiscExpencesHeads");
                });

            modelBuilder.Entity("DataAccess.Models.MiscIncomeDetail", b =>
                {
                    b.Property<int>("MiscIncomeDetailID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("MiscIncomeDetailID");

                    b.ToTable("MiscIncomeDetails");
                });

            modelBuilder.Entity("DataAccess.Models.MiscIncomeHead", b =>
                {
                    b.Property<int>("MiscIncomeHeadID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("MiscIncomeHeadID");

                    b.ToTable("MiscIncomeHeads");
                });

            modelBuilder.Entity("DataAccess.Models.SrnDetail", b =>
                {
                    b.Property<int>("SrnDetailID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("SrnDetailID");

                    b.ToTable("SrnDetails");
                });

            modelBuilder.Entity("DataAccess.Models.SrnHead", b =>
                {
                    b.Property<int>("SrnHeadID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("SrnHeadID");

                    b.ToTable("SrnHeads");
                });

            modelBuilder.Entity("DataAccess.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("SupplierID");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("DataAccess.Models.CustReceiptHead", b =>
                {
                    b.HasOne("DataAccess.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataAccess.Models.GrnDetail", b =>
                {
                    b.HasOne("DataAccess.Models.GrnHead")
                        .WithMany("GrnDetails")
                        .HasForeignKey("GrnHeadID");
                });

            modelBuilder.Entity("DataAccess.Models.Item", b =>
                {
                    b.HasOne("DataAccess.Models.ItemCategory")
                        .WithMany("Items")
                        .HasForeignKey("ItemCategoryCatCode");
                });
#pragma warning restore 612, 618
        }
    }
}
